# This is a TOML document

[main]
# Interface where the simulator will send and receive packets
NetIface = "enp0s25"
# Amounts of workers used to process tasks
WorkersCount = 10

[log]
# 
File = "/tmp/log.txt"
# const (
#     CRITICAL Level = iota
#     ERROR
#     WARNING
#     NOTICE
#     INFO
#     DEBUG
# )
Level = 6
# Example format string. Everything except the message has a custom color
# which is dependent on the log level. Many fields have a custom output
# formatting too, eg. the time returns the hour down to the milli second.
Formatter = "%{color}[%{time:15:04:05.000} %{shortfunc} ▶ %{level:.8s} %{id:03x}%{color:reset}] %{message}"
